In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:/Users/harri/Documents/nfl-playbyplay-predictor/data/pbp_export.csv")

In [ ]:
#Shows the first five plays of the 2020 NFL season
df.head()

,play_id,game_id,season,play_type,down,ydstogo,yardline_100,score_differential,game_seconds_remaining,offense_personnel,defense_personnel,posteam
0,1,2020_01_ARI_SF,2020,NaN,NaN,0,NaN,NaN,3600.0,NaN,NaN,NaN
1,39,2020_01_ARI_SF,2020,kickoff,NaN,0,35.0,0.0,3600.0,NaN,NaN,SF
2,54,2020_01_ARI_SF,2020,pass,1.0,10,75.0,0.0,3600.0,"2 RB, 1 TE, 2 WR","2 DL, 5 LB, 4 DB",SF
3,93,2020_01_ARI_SF,2020,run,1.0,10,55.0,0.0,3582.0,"2 RB, 1 TE, 2 WR","2 DL, 5 LB, 4 DB",SF
4,118,2020_01_ARI_SF,2020,run,1.0,10,41.0,0.0,3539.0,"2 RB, 1 TE, 2 WR","2 DL, 5 LB, 4 DB",SF

In [4]:
df.describe()

,play_id,season,down,ydstogo,yardline_100,score_differential,game_seconds_remaining
count,196726.000000,196726.000000,165330.000000,196726.000000,182854.000000,186098.000000,196713.000000
mean,2117.833738,2021.513704,1.992155,7.101659,48.445388,-1.323023,1705.855480
std,1237.474701,1.113429,1.001704,4.861211,24.290279,10.472587,1059.715258
min,1.000000,2020.000000,1.000000,0.000000,1.000000,-56.000000,0.000000
25%,1053.000000,2021.000000,1.000000,3.000000,31.000000,-7.000000,782.000000
50%,2103.000000,2022.000000,2.000000,9.000000,50.000000,0.000000,1800.000000
75%,3155.000000,2023.000000,3.000000,10.000000,70.000000,4.000000,2598.000000
max,5523.000000,2023.000000,4.000000,43.000000,99.000000,55.000000,3600.000000